name: "Check for website health"

on:
  schedule:
    - cron: "26 23 * * *"
  workflow_dispatch:
    
jobs:
  health_check_badge_job:
    runs-on: ubuntu-latest
    name: Check status of GC server
    steps:
      - name: Health check
        uses: 102/website-healthcheck@v1.0.2        
        with:
          web-url: https://gridfinity.bouwens.co
          
